config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :bookmarks, only: [:index]

  resources :books do
    resources :comments, only: %i[create]
    resource :bookmark, only: %i[create destroy]
    member do
      patch :like
      post :borrow
      post :return
      post :bookmark
    end
    resources :ratings, only: %i[create]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/layouts/_average_rating.html.erb
<div class="average-rating">
  <span class="stars">
    <% (1..5).each do |star| %>
      <% if book.average_rating >= star %>
        <span class="rating-star filled-star">★</span>
      <% else %>
        <span class="rating-star empty-star">☆</span>
      <% end %>
    <% end %>
  </span>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice]%>
    <div class="alert alert-info" role="alert">
        <%= notice %>
    </div>
<% end%>
  <% if flash[:alert]%>
    <div class="alert alert-danger" role="alert">
        <%= alert %>
    </div>
<% end%>

app/views/layouts/_likes.html.erb
<%= tag.div id: dom_id(book, :likes), class: "d-flex" do %>
  <%= button_to like_book_path(book), method: :patch, remote: true, class: "border-0 bg-transparent svg-icon" do %>
    <% if book.liked_by?(current_user) %>
      <i class="bi bi-suit-heart-fill svg-red"></i>
    <% else %>
      <i class="bi bi-suit-heart"></i>
    <% end %>
  <% end %>
  <p class="main-color"><%= book.likes_count %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="<%= root_path %>">
        <i class="bi bi-book"></i>
      </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= books_path %>">Books</a>
        </li>
      </ul>
    </div>
    <div class="bookmark mx-2">
      <%= link_to bookmarks_path  do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
          <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
        </svg>
      <% end %>
    </div>
    <div class="d-flex align-items-center">
      <% if current_user %>
        <div class="dropdown">
          <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="userMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userMenuButton">
            <li>
              <%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to 'Settings', '#', class: 'dropdown-item' %>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <%= button_to t(".sign_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </li>
          </ul>
        </div>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to t(".sign_up"), new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to t(".sign_in"), new_user_session_path, class: "nav-link" %></li>
        </ul>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/_rating.html.erb
<div class="d-flex justify-content-center">
  <div class="text-center mb-5">
    <%= form_with model: [book, Rating.new], local: true do |f| %>
      <div class="rating">
        <% user_rating = book.ratings.where(user: current_user).first&.stars || 0%>

        <div class="rating">
          <% (1..5).reverse_each do |stars| %>
            <%= f.radio_button :stars, stars, id: "rating_#{stars}", checked: (user_rating == stars) %>
            <%= f.label :stars, '☆', for: "rating_#{stars}" %>
          <% end %>
        </div>
      </div>
    <div class="buttons mt-0">
        <%= f.submit "Submit", class: "btn btn-info px-4 py-1" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: 'layouts/navbar' %>
    <div class="container mt-2">
      <% unless current_page?(root_path) %>
        <div class="breadcrumbs">
          <div class="breadcrumbs-inner px-3 py-1">
            <%= render_breadcrumbs :separator => ' / ' %>
          </div>
        </div>
      <% end %>
      <%= render partial: "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>